const TOKEN = 'TOKEN';
const REFRESH_TOKEN = 'REFRESH_TOKEN';
const EXPIRED_TIME = 'EXPIRED_TIME';

export { TOKEN, REFRESH_TOKEN, EXPIRED_TIME };
export default { TOKEN, REFRESH_TOKEN, EXPIRED_TIME };
